# Generated by Django 6.0.3 on 2026-03-13 00:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
        ('contacts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='owner',
        ),
        migrations.AddField(
            model_name='asset',
            name='owner_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_assets', to='contacts.contact'),
        ),
        migrations.AddField(
            model_name='asset',
            name='responsible_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_assets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Activo'), ('INACTIVE', 'Inactivo'), ('RETIRED', 'Retirado')], default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(choices=[('HARDWARE', 'Hardware'), ('SOFTWARE', 'Software'), ('SERVICE', 'Servicio'), ('INFRASTRUCTURE', 'Infraestructura')], max_length=50),
        ),
        migrations.AlterField(
            model_name='asset',
            name='classification',
            field=models.CharField(choices=[('PUBLIC', 'Publico'), ('INTERNAL', 'Interno'), ('CONFIDENTIAL', 'Confidencial'), ('RESTRICTED', 'Restringido')], default='INTERNAL', max_length=50),
        ),
    ]
