# Generated by Django 6.0.3 on 2026-03-13 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
        ('projects', '0002_projectuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='start_date',
        ),
        migrations.AddField(
            model_name='project',
            name='actual_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de fin real'),
        ),
        migrations.AddField(
            model_name='project',
            name='actual_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de inicio real'),
        ),
        migrations.AddField(
            model_name='project',
            name='planned_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de fin planeada'),
        ),
        migrations.AddField(
            model_name='project',
            name='planned_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de inicio planeada'),
        ),
        migrations.AlterField(
            model_name='projectuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrador del Proyecto'), ('CONSULTANT', 'Consultor'), ('CLIENT', 'Cliente'), ('VIEWER', 'Observador')], default='CLIENT', max_length=20, verbose_name='Rol en el proyecto'),
        ),
        migrations.CreateModel(
            name='ProjectContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_role', models.CharField(choices=[('PROJECT_MANAGER', 'Gestor Proyecto'), ('CISO', 'CISO'), ('IT_MANAGER', 'Gerente TI'), ('CONSULTANT', 'Consultor')], max_length=30, verbose_name='Rol del contacto')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Es contacto principal')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_contacts', to='contacts.contact', verbose_name='Contacto')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_contacts', to='projects.project', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Contacto de Proyecto',
                'verbose_name_plural': 'Contactos de Proyecto',
                'db_table': 'projects_projectcontact',
                'ordering': ['-created_at'],
                'unique_together': {('project', 'contact')},
            },
        ),
    ]
