# Generated by Django 6.0.3 on 2026-03-16 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_project_end_date_remove_project_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcontact',
            name='work_notes',
            field=models.TextField(blank=True),
        ),
    ]
