# Generated by Django 6.0.3 on 2026-03-16 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='work_notes',
            field=models.TextField(blank=True),
        ),
    ]
