# Generated by Django 6.0.3 on 2026-03-13 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phases', '0001_initial'),
        ('projects', '0003_remove_project_end_date_remove_project_start_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phase',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='phase',
            name='start_date',
        ),
        migrations.AddField(
            model_name='phase',
            name='actual_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='phase',
            name='actual_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='phase',
            name='planned_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='phase',
            name='planned_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='phase',
            constraint=models.UniqueConstraint(fields=('project', 'order'), name='uniq_phase_project_order'),
        ),
    ]
