# Generated by Django 6.0.3 on 2026-03-13 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='completion_date',
        ),
        migrations.RemoveField(
            model_name='task',
            name='due_date',
        ),
        migrations.AddField(
            model_name='task',
            name='actual_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de fin real'),
        ),
        migrations.AddField(
            model_name='task',
            name='actual_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de inicio real'),
        ),
        migrations.AddField(
            model_name='task',
            name='planned_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de fin planeada'),
        ),
        migrations.AddField(
            model_name='task',
            name='planned_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de inicio planeada'),
        ),
        migrations.AddField(
            model_name='task',
            name='work_notes',
            field=models.TextField(blank=True, verbose_name='Notas de trabajo'),
        ),
    ]
