# Generated by Django 6.0.3 on 2026-03-13 00:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('phases', '0002_remove_phase_end_date_remove_phase_start_date_and_more'),
        ('projects', '0003_remove_project_end_date_remove_project_start_date_and_more'),
        ('tasks', '0002_remove_task_completion_date_remove_task_due_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('doc_type', models.CharField(choices=[('ISO_CONTROL_EVIDENCE', 'Evidencia control'), ('POLICY', 'Politica'), ('PROCEDURE', 'Procedimiento'), ('REPORT', 'Informe'), ('OTHER', 'Otro')], max_length=30)),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('IN_REVIEW', 'En revision'), ('APPROVED', 'Aprobado')], default='DRAFT', max_length=20)),
                ('file', models.FileField(upload_to='documents/')),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_documents', to=settings.AUTH_USER_MODEL)),
                ('phase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='phases.phase')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='projects.project')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='tasks.task')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'db_table': 'documents_document',
                'ordering': ['-created_at'],
            },
        ),
    ]
