# Generated by Django 6.0.3 on 2026-03-16 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='actual_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='planned_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
